package com.pojos;
// Generated 01/04/2016 05:12:53 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tactividad generated by hbm2java
 */
public class Tactividad  implements java.io.Serializable {


     private String codigoActividad;
     private Tusuario tusuario;
     private String nombre;
     private String descripcion;
     private Date fechaInicio;
     private Date fechaFin;
     private BigDecimal presupuestoTotal;
     private char estado;
     private Date fechaRegistro;
     private Date fechaModificacion;
     private Set tactividadPresupuestos = new HashSet(0);
     private Set tactividadComentarios = new HashSet(0);
     private Set tactividadParticipantes = new HashSet(0);

    public Tactividad() {
    }

	
    public Tactividad(String codigoActividad, Tusuario tusuario, String nombre, String descripcion, Date fechaInicio, Date fechaFin, BigDecimal presupuestoTotal, char estado) {
        this.codigoActividad = codigoActividad;
        this.tusuario = tusuario;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
        this.presupuestoTotal = presupuestoTotal;
        this.estado = estado;
    }
    public Tactividad(String codigoActividad, Tusuario tusuario, String nombre, String descripcion, Date fechaInicio, Date fechaFin, BigDecimal presupuestoTotal, char estado, Date fechaRegistro, Date fechaModificacion, Set tactividadPresupuestos, Set tactividadComentarios, Set tactividadParticipantes) {
       this.codigoActividad = codigoActividad;
       this.tusuario = tusuario;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.presupuestoTotal = presupuestoTotal;
       this.estado = estado;
       this.fechaRegistro = fechaRegistro;
       this.fechaModificacion = fechaModificacion;
       this.tactividadPresupuestos = tactividadPresupuestos;
       this.tactividadComentarios = tactividadComentarios;
       this.tactividadParticipantes = tactividadParticipantes;
    }
   
    public String getCodigoActividad() {
        return this.codigoActividad;
    }
    
    public void setCodigoActividad(String codigoActividad) {
        this.codigoActividad = codigoActividad;
    }
    public Tusuario getTusuario() {
        return this.tusuario;
    }
    
    public void setTusuario(Tusuario tusuario) {
        this.tusuario = tusuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public BigDecimal getPresupuestoTotal() {
        return this.presupuestoTotal;
    }
    
    public void setPresupuestoTotal(BigDecimal presupuestoTotal) {
        this.presupuestoTotal = presupuestoTotal;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set getTactividadPresupuestos() {
        return this.tactividadPresupuestos;
    }
    
    public void setTactividadPresupuestos(Set tactividadPresupuestos) {
        this.tactividadPresupuestos = tactividadPresupuestos;
    }
    public Set getTactividadComentarios() {
        return this.tactividadComentarios;
    }
    
    public void setTactividadComentarios(Set tactividadComentarios) {
        this.tactividadComentarios = tactividadComentarios;
    }
    public Set getTactividadParticipantes() {
        return this.tactividadParticipantes;
    }
    
    public void setTactividadParticipantes(Set tactividadParticipantes) {
        this.tactividadParticipantes = tactividadParticipantes;
    }




}


