package com.pojos;
// Generated 01/04/2016 05:12:53 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TunidadMedida generated by hbm2java
 */
public class TunidadMedida  implements java.io.Serializable {


     private String codigoUnidadMedida;
     private String nombre;
     private String descripcion;
     private Date fechaRegistro;
     private Date fechaModificacion;
     private Set tactividadPresupuestos = new HashSet(0);

    public TunidadMedida() {
    }

	
    public TunidadMedida(String codigoUnidadMedida, String nombre, String descripcion) {
        this.codigoUnidadMedida = codigoUnidadMedida;
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
    public TunidadMedida(String codigoUnidadMedida, String nombre, String descripcion, Date fechaRegistro, Date fechaModificacion, Set tactividadPresupuestos) {
       this.codigoUnidadMedida = codigoUnidadMedida;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.fechaRegistro = fechaRegistro;
       this.fechaModificacion = fechaModificacion;
       this.tactividadPresupuestos = tactividadPresupuestos;
    }
   
    public String getCodigoUnidadMedida() {
        return this.codigoUnidadMedida;
    }
    
    public void setCodigoUnidadMedida(String codigoUnidadMedida) {
        this.codigoUnidadMedida = codigoUnidadMedida;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set getTactividadPresupuestos() {
        return this.tactividadPresupuestos;
    }
    
    public void setTactividadPresupuestos(Set tactividadPresupuestos) {
        this.tactividadPresupuestos = tactividadPresupuestos;
    }




}


