package com.pojos;
// Generated 18/03/2016 04:48:44 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TusuarioAmigoTelefono generated by hbm2java
 */
public class TusuarioAmigoTelefono  implements java.io.Serializable {


     private String codigoUsuarioAmigoTelefono;
     private TusuarioAmigo tusuarioAmigo;
     private String descripcion;
     private String telefono;
     private Date fechaRegistro;
     private Date fechaModificacion;

    public TusuarioAmigoTelefono() {
    }

    public TusuarioAmigoTelefono(String codigoUsuarioAmigoTelefono, TusuarioAmigo tusuarioAmigo, String descripcion, String telefono, Date fechaRegistro, Date fechaModificacion) {
       this.codigoUsuarioAmigoTelefono = codigoUsuarioAmigoTelefono;
       this.tusuarioAmigo = tusuarioAmigo;
       this.descripcion = descripcion;
       this.telefono = telefono;
       this.fechaRegistro = fechaRegistro;
       this.fechaModificacion = fechaModificacion;
    }
   
    public String getCodigoUsuarioAmigoTelefono() {
        return this.codigoUsuarioAmigoTelefono;
    }
    
    public void setCodigoUsuarioAmigoTelefono(String codigoUsuarioAmigoTelefono) {
        this.codigoUsuarioAmigoTelefono = codigoUsuarioAmigoTelefono;
    }
    public TusuarioAmigo getTusuarioAmigo() {
        return this.tusuarioAmigo;
    }
    
    public void setTusuarioAmigo(TusuarioAmigo tusuarioAmigo) {
        this.tusuarioAmigo = tusuarioAmigo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


